
export const CLEAR_DATA = "CLEAR_DATA"
export const GET_VENUES_LIST = "GET_VENUES_LIST"
export const ADD_NEW_PARTICIPANT = "ADD_NEW_PARTICIPANT"
export const UPDATE_PARTICIPANT_SELECTED_VENUE = "UPDATE_PARTICIPANT_SELECTED_VENUE"
